import React from 'react'
import RenewableEnergy from './RenewableEnergy'
export const metadata = {
  title: "Renewable Energy",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <RenewableEnergy></RenewableEnergy>
    </div>
  )
}

export default page
