import React from 'react'
import Blogs from './Blogs'
export const metadata = {
  title: "Blogs",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <Blogs></Blogs>
    </div>
  )
}

export default page
