import React from 'react'
import AboutMe from './AboutMe'
export const metadata = {
  title: "About me",
  description: "Generated by create next app",
  // schema:`<script id-json>
  // DDFGJggsdgs
  // </script>`
};
const page = () => {
  return (
    <div>
      <AboutMe></AboutMe>
    </div>
  )
}

export default page
