import React from 'react'
import UnifiedInvestmentsLLCDubai from './UnifiedInvestmentsLLCDubai'
export const metadata = {
  title: "Unified Investments LLC Dubai",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <UnifiedInvestmentsLLCDubai></UnifiedInvestmentsLLCDubai>
    </div>
  )
}

export default page
