import React from 'react'
import UnifiedPropertiesDubai from './UnifiedPropertiesDubai'
export const metadata = {
  title: "Unified Properties Dubai",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
    <UnifiedPropertiesDubai></UnifiedPropertiesDubai>
    </div>
  )
}

export default page
