import React from 'react'
import HaitchHoldingsDIFCDubai from './HaitchHoldingsDIFCDubai'
export const metadata = {
  title: "Haitch Holdings DIFC Dubai",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <HaitchHoldingsDIFCDubai></HaitchHoldingsDIFCDubai>
    </div>
  )
}

export default page
