import React from 'react'
import Education from './Education'
export const metadata = {
  title: "Education",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <Education></Education>
    </div>
  )
}

export default page
