import React from 'react'
import Post2 from './Post2';

export const metadata = {
  title: "Post2",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <Post2></Post2>
    </div>
  )
}

export default page
