import React from 'react'
import Post1 from './post1'
export const metadata = {
  title: "Post1",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <Post1></Post1>
    </div>
  )
}

export default page
