import React from 'react'
import UnifiedCapitalAndInvestmentIndia from './UnifiedCapitalAndInvestmentIndia'
export const metadata = {
  title: "Unified Capital And Investment India",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <UnifiedCapitalAndInvestmentIndia></UnifiedCapitalAndInvestmentIndia>
    </div>
  )
}

export default page
