import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import MobileMenuNew from "./mobileMenu/mobileMenu";
import Footer from "./footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={inter.className}>
      <div className="">
      <Header/>
      <div className="lg:hidden fixed w-full -top-2 z-[100] ">
        {/* <MobileMenuNew/> */}
        </div>
      {children}
      <Footer></Footer>
      </div>
      </body>
    </html>
  );
}
