import Homepage from "./homepage/page";
export const metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default function Home() {
  return (
 <div className="home ">

<Homepage></Homepage>
 </div> 
  );
}
