import React from 'react'
import TourismAndHospitality from './TourismAndHospitality'
export const metadata = {
  title: "Tourism and Hospitality",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <TourismAndHospitality/>
    </div>
  )
}

export default page
