import React from 'react'
import MediaDynoxPrivateLimitedIndia from './MediaDynoxPrivateLimitedIndia'
export const metadata = {
  title: "Media Dynox Private  Limited India",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <MediaDynoxPrivateLimitedIndia></MediaDynoxPrivateLimitedIndia>
    </div>
  )
}

export default page
