import React from 'react'
import RealEstate from './RealEstate'

export const metadata = {
  title: "Real Estate",
  description: "Generated by create next app",
};


const page = () => {
  return (
    <div>
      <RealEstate></RealEstate>
    </div>
  )
}

export default page
