import React from 'react'
import CatsClubsAndBarPhilippines from './CatsClubsAndBarPhilippines'
export const metadata = {
  title: "Cats Clubs And Bar Philippines",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <CatsClubsAndBarPhilippines></CatsClubsAndBarPhilippines>
    </div>
  )
}

export default page
