import React from 'react'
import StockMarket from './StockMarket'

export const metadata = {
  title: "Stock Market",
  description: "Generated by create next app",
};


const page = () => {
  return (
    <div>
      <StockMarket></StockMarket>
    </div>
  )
}

export default page
