import React from 'react'
import DynoxMediaLLCDubai from './DynoxMediaLLCDubai'
export const metadata = {
  title: "Dynox Media LLC Dubai",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <DynoxMediaLLCDubai></DynoxMediaLLCDubai>
    </div>
  )
}

export default page
