import React from 'react'
import CatsClubAndBarDubai from './CatsClubAndBarDubai'
export const metadata = {
  title: "Cats Clubs and Bar Dubai",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
  <CatsClubAndBarDubai></CatsClubAndBarDubai>
    </div>
  )
}

export default page
