import React from 'react'
import UnifiedChelseaPlazaHotel from './UnifiedChelseaPlazaHotel'
export const metadata = {
  title: "Unified Chelsea Plaza Hotel",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <UnifiedChelseaPlazaHotel></UnifiedChelseaPlazaHotel>
    </div>
  )
}

export default page
