import React from 'react'
import Healthcare from './Healthcare'

export const metadata = {
  title: "Healthcare",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <Healthcare/>
    </div>
  )
}

export default page
