import React from 'react'
import Post3 from './Post3'
export const metadata = {
  title: "Post3",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <Post3></Post3>
    </div>
  )
}

export default page
