import React from 'react'
import UnifiedEventsAndHospitalityDubai from './UnifiedEventsAndHospitalityDubai'
export const metadata = {
  title: "Unified Events And Hospitality Dubai",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <UnifiedEventsAndHospitalityDubai></UnifiedEventsAndHospitalityDubai>
    </div>
  )
}

export default page
