import React from 'react'
import ContactUs from './ContactUs'

export const metadata = {
  title: "Contact Us",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <ContactUs></ContactUs>
    </div>
  )
}

export default page
