import React from 'react'
import BusinessSetup from './businessSetup'
export const metadata = {
  title: "Business Setup",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <BusinessSetup/>
    </div>
  )
}

export default page
