
import React from 'react'
import Insights from './Insights'
export const metadata = {
  title: "Insights",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <Insights/>
    </div>
  )
}

export default page
