import React from 'react'
import Infrastructure from './Infrastructure'
export const metadata = {
  title: "Infrastructure",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <Infrastructure></Infrastructure>
    </div>
  )
}

export default page
